gcp-auth:
  image: google/cloud-sdk:slim
  when: manual
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud:  
        - https://gitlab.fdmci.hva.nl
  tags:
    - hva 
  script:
    - chmod +x ./get_token.sh
    - ./get_token.sh   
    - gcloud config set auth/access_token_file $(pwd)/gcp_temp_token.txt
    - gcloud auth list
    - gcloud config set project "gcp-hva-hbo-ict-prgr-1" 
    - gcloud iam service-accounts list